EFRelationships.Web/Models/ErrorViewModel.cs
using System;

namespace EFRelationships.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EFRelationships.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EFRelationships.Web.Models;
using EFRelationships.Data;
using Microsoft.Extensions.Configuration;

namespace EFRelationships.Web.Controllers
{
    public class HomeController : Controller
    {
        private string _connectionString;
        public HomeController(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("ConStr");
        }

        public IActionResult Index()
        {
            var repo = new PeopleCarsRepository(_connectionString);
            return View(repo.GetPeople());
        }

        public IActionResult AddCar(int personId)
        {
            var repo = new PeopleCarsRepository(_connectionString);
            var person = repo.GetPerson(personId);
            return View(person);
        }

        [HttpPost]
        public IActionResult AddCar(Car car)
        {
            var repo = new PeopleCarsRepository(_connectionString);
            repo.AddCar(car);
            return RedirectToAction("Index");
        }

        public IActionResult Losers()
        {
            var repo = new PeopleCarsRepository(_connectionString);
            return View(repo.GetPeopleWithNoCars());
        }
    }
}

EFRelationships.Web/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using EFRelationships.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace EFRelationships.Web.Controllers
{
    public class QuestionsController : Controller
    {
        private string _connectionString;

        public QuestionsController(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("ConStr");
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Question question, IEnumerable<string> tags)
        {
            question.DatePosted = DateTime.Now;
            var repo = new QuestionsRepository(_connectionString);
            repo.AddQuestion(question, tags);
            return Redirect("/questions");
        }
    }
}

EFRelationships.Web/Views/Home/AddCar.cshtml
@model EFRelationships.Data.Person

<div class="row">
    <div class="col-md-6 col-md-offset-3 well">

        <h2>Adding car for @Model.FirstName @Model.LastName</h2>
        <form method="post" action="/home/addcar">
            <input type="hidden" name="personId" value="@Model.Id" />
            <input class="form-control" type="text" name="make" placeholder="Make" />
            <br />
            <input class="form-control" type="text" name="model" placeholder="Model" />
            <br />
            <input class="form-control" type="text" name="year" placeholder="Year" />
            <br />
            <button class="btn btn-primary">Add Car</button>
        </form>
    </div>
</div>

EFRelationships.Web/Views/Home/Index.cshtml
@using EFRelationships.Data
@model IEnumerable<Person>
<table class="table table-bordered">
    <tr>
        <th>Add Car</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Car Count</th>
    </tr>
    @foreach (Person person in Model)
    {
        <tr>
            <td>
                <a href="/home/addcar?personid=@person.Id" class="btn btn-primary">Add Car</a>
            </td>
            <td>@person.FirstName</td>
            <td>@person.LastName</td>
            <td>@person.Age</td>
            <td>@person.Cars.Count</td>
        </tr>
    }
</table>

EFRelationships.Web/Views/Home/Losers.cshtml
@using EFRelationships.Data
@model IEnumerable<Person>


<h1>People with no cars :(</h1>

<table class="table table-bordered">
    <tr>
        <th>Add Car</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Car Count</th>
    </tr>
    @foreach (Person person in Model)
    {
        <tr>
            <td>
                <a href="/home/addcar?personid=@person.Id" class="btn btn-primary">Add Car</a>
            </td>
            <td>@person.FirstName</td>
            <td>@person.LastName</td>
            <td>@person.Age</td>
            <td>@person.Cars.Count</td>
        </tr>
    }
</table>

EFRelationships.Web/Views/Questions/Index.cshtml
<div class="row col-md-6 col-md-offset-3 well">
    <form method="post" action="/questions/add">
        <input class="form-control" name="title" placeholder="Title" />
        <br />
        <textarea class="form-control" placeholder="Type your question here..." rows="10" name="text"></textarea>
        <br />
        <select multiple class="form-control" id="tags" name="tags"></select>
        <br />
        <button class="btn btn-primary">Submit</button>
    </form>
</div>

@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.js"></script>
    <script>
        $(() => {
            $("#tags").tagsinput();
        })
    </script>
}

@section styles
    {
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css" />
}

EFRelationships.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EFRelationships.Web</title>
    @RenderSection("styles", false)
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EFRelationships.Web</a>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Questions" asp-action="Index">Questions</a></li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container" style="margin-top: 60px;">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>